# This is a basic workflow to help you get started with Actions

name: Pull Request updated
# Controls when the action will run. 
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]


jobs:
  history:
    name: Pull Request Body
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request Body
        uses: technote-space/pr-commit-body-action@v1
